services:
  storystash:
    container_name: StoryBox
    build: .
    network_mode: host 
    
    # NOTE: When using network_mode: host, we do NOT use the 'ports' section.
    # The app will automatically be available on port 8000.
    
    volumes:
      - ./data:/app/data
      - ./stories:/app/stories
      - ./avatars:/app/avatars
      - ./gallery:/app/gallery
      - ./backgrounds:/app/backgrounds
    restart: unless-stopped
